### ISSUE TITLE
Remove multi character support

### ISSUE THREAD

**Issue by ElPumpo** [ESX-Org/esx_identity#29]

**Comment by ArkSeyonet** [comment]
Is the plan in the end to only have support for 1 character? I would like to know if that is the plan for ESX since I am working on my AIOMenu script again, and it will make it easier for me since I can just use this version of esx_identity instead of my older version that doesn't look nearly as good as you have all made it look.

**Comment by ElPumpo** [comment]
Yes the plan is to end multiple characters.. When? Idk

It has always been an half-baked feature, and only changes name, age, sex and height..

**Comment by HumanTree92** [comment]
Multiple characters are just a pain. I have it set where players can't delete their character but must ask a staff member to delete their character as we had problems where players would rack up citations in our CAD & they would delete their characters to become clean. But yeah 1 character is all players need. They don't like it to bad.

**Comment by RichardBiggs** [comment]
I've accomplished this for the mean time by changing line 250 in the server.lua to data.firstname1 instead of 3. Changing line 251 to a proper chat message. Removing the updateIdentity function. Lastly removing the chardel, charselect and charlist commands. I'm not very experienced in scripting so I'm not sure if it can be done better, however this does function for me. I'd be happy to share my solution with the OP if it would be of any help.
